### ISSUE TITLE
Faster Code?

### ISSUE THREAD

**Issue by jcriddle4** [cair/fast-tsetlin-machine-in-cuda-with-imdb-demo#1]
I was playing with a C(non-Cuda) version of this on my system and found the initialization of la_feedback was quite expensive. I more then double my speed by optimizing it. I am not sure if it is as expensive on Cuda or not. I wonder if the following pseudo code might be much faster or maybe the way cuda works this wouldn't help? Hopefully I haven't optimized so far that it is wrong. I am assuming that S is an integer rather than a float. NOTE: S scales differently(See comment below). 

```
int la_feedback = 0;  
int next = 0; 
while(next < INT_SIZE){
    int r = cuda_random_int_function(...) % (S + 1));
    if(r == S){  		
	next += (r - 1);  //Skip setting any of the bits in the range of S. 
    } else if(next + r < INT_SIZE){
        next += r;
    	la_feedback |= (1 << to_integer(next % INT_SIZE);  //Set one of the bits
    }
}
```

**Comment by jcriddle4** [comment]
Hummm... If we want an approximately similar distribution to the old code and if my binomial distribution calculations are correct for a value like S=10 the code would look something like this. Is this over thinking it? Do we care if S's values scale differently?

    ...
    r = random() % (s+**4**);
    ...
    if(r **>**= s){ 
        next += (s - 1);  //Skip setting any bits.
    }
    ....

**Comment by olegranmo** [comment]
Thanks for very useful ideas @jcriddle4. Significantly increased learning speed. Ole-Christoffer
